version: "3.9"

name: fit-tracker

services:
  database:
    container_name: fit-tracker-postgres
    image: postgres:16-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file: .env

volumes:
  postgres_db:
