# Generated by Django 4.2 on 2024-04-05 18:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workout", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WorkoutProgram",
            new_name="Workout",
        ),
        migrations.RenameField(
            model_name="workoutsession",
            old_name="program",
            new_name="workout",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="equipment_required",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="muscle_group",
        ),
        migrations.RemoveField(
            model_name="set",
            name="weight",
        ),
        migrations.DeleteModel(
            name="Equipment",
        ),
        migrations.DeleteModel(
            name="MuscleGroup",
        ),
    ]
