# Generated by Django 4.2 on 2024-04-06 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workout", "0002_rename_workoutprogram_workout_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="exercises",
            field=models.ManyToManyField(
                blank=True, related_name="workouts", to="workout.exercise"
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workouts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
